hasura:
  replicas: 1
  service:
    nodePort: 30139

tezos-marketplace-indexer-rarible:
  replicas: 1
  environments: 
    TZKT_URL: http://tzkt:5000
    NETWORK: mainnet
    LEGACY_API: https://tezos-api.rarible.org

tezos-marketplace-indexer-tezos:
  replicas: 1
  environments:
    TZKT_URL: http://tzkt:5000
    NETWORK: mainnet
    LEGACY_API: https://tezos-api.rarible.org
  resources:
     requests:
       cpu: '1'
       memory: 2Gi
     limits:
       cpu: '1'
       memory: 2Gi

tzkt:
  enabled: true
  api:
    resources:
      limits:
        cpu: '1'
        memory: 3Gi
      requests:
        cpu: 200m
        memory: 1384Mi
    image:
      repository: mystdeim/tzkt-api
      tag: 0.2
  indexer:
    resources:
      limits:
        cpu: 400m
        memory: 2Gi
      requests:
        cpu: 200m
        memory: 384Mi
  network: mainnet
  service:
    nodePort: 30140
  environments:
    TezosNode__Endpoint: https://rpc.tzkt.io/mainnet
    TokenMetadata__DipDup__Url: https://metadata.dipdup.net/v1/graphql
  ingress:
    hostname: 'tezos-tzkt.rarible.int'
    path: /
    ingressClassName: ingress-internal
    backend:
      service: tzkt
      port: http